name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: moss/xelatex:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build PDF
        run: xelatex cv.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf
